version: '3'
services:
  app:
    container_name: mutagen-powered-app
    environment:
      # This variable is required to run local setup on Linux, determines the switch from root to user
      - LOCAL=true
    volumes:
      # PHP configuration mount
      - ./deploy/shared/conf/php/php.ini:/usr/local/etc/php/php.ini
      # PHP FPM pool settings
      - ./deploy/shared/conf/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      # Uncomment to use custom configuration with -debug image
      - ./deploy/shared/conf/xdebug/xdebug-config.ini:/usr/local/etc/php/conf.d/xdebug-config.ini
      # Uncomment line below only for testing launch script without rebuild
      # - ./deploy/mutagen/start.sh:/start.sh
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTICSEARCH_VERSION}
    restart: on-failure:5
    environment:
      - xpack.security.enabled=false
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - default
  maildev:
    image: djfarrelly/maildev
    ports:
      - ${MAILDEV_PORT}:80
    expose:
      - 25
    links:
      - nginx:webserver
    command: ["bin/maildev", "--web", "80", "--smtp", "25", "--base-pathname", "/maildev/"]
    networks:
      - default
