version: '3'
services:
  nginx:
    volumes:
      - ./deploy/frontend/conf/nginx/cache-router.conf:/etc/nginx/conf.d/cache-router.conf
    links:
      - frontend
  frontend:
    image: scandipwa/frontend:${PROJECT_IMAGE}
    build:
      context: build/frontend
      args:
        - NODEJS_VERSION=${NODEJS_VERSION}
    volumes:
      - app-data:/var/www/public
    env_file: .env
    environment: 
      - PROCESS_FILE=${FRONTEND_CORE_PROCESS_FILE}
    working_dir: "/var/www/public/localmodules/base-theme/"
    command: ["/bin/bash", "/start.sh"]
    expose:
      - 3003
  app:
    command: ["/wait-for-it.sh", "mysql:3306", "--", "/start-with-mutagen-when-frontend-serving.sh"]

