<?php
    $colorConfig = $this->getThemeConfiguration('color_customization');
    $contentConfig = $this->getThemeConfiguration('content_customization');
?>

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">

        <script>
            if ('serviceWorker' in navigator) {
                window.addEventListener('load', function() {
                    navigator.serviceWorker.register('/sw.js');
                });
            }

            window.actionName = {
                type: `<?= $this->getAction(); ?>`
            };

            window.contentConfiguration = <?= json_encode($contentConfig) ?> || {};
        </script>
        <script async src="<?= $this->getStaticFile("assets/pwacompat.min.js"); ?>"></script>

        <!-- TODO: Find or implement helper to generate fonts related code -->
        <link rel="preload" href="<%= htmlWebpackPlugin.options.publicPath %>assets/font/Roboto-Regular.woff2" as="font" type="font/woff2" crossorigin="">
        <link rel="preload" href="<%= htmlWebpackPlugin.options.publicPath %>assets/font/Oswald-Bold.woff2" as="font" type="font/woff2" crossorigin="">

        <style>
            @font-face {
                font-family: 'Roboto';
                font-style: normal;
                font-weight: 400;
                font-display: fallback;
                src: url(<%= htmlWebpackPlugin.options.publicPath %>assets/font/Roboto-Regular.woff2) format('woff2');
                unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
            }

            @font-face {
                font-family: 'Oswald';
                font-style: normal;
                font-weight: 700;
                font-display: fallback;
                src: url(<%= htmlWebpackPlugin.options.publicPath %>assets/font/Oswald-Bold.woff2) format('woff2');
                unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
            }
        </style>

        <link rel="shortcut icon" href="<?= $this->getStaticFile("assets/favicon/favicon.ico"); ?>">

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover">
    </head>

    <body>
        <noscript> You need to enable JavaScript to run this app. </noscript>
        <div id="root"></div>
        <script src="<?= $this->getStaticBundleFile() ?>"></script>
    </body>
</html>
